//core imports
import React, { Fragment } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'

//components
import Header from '../header/Header'
import Footer from '../footer/Footer'

export default function Layout( { children } ) {
    const router = useRouter()
    return (
        <Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>{ children }</main>
            <Footer />
        </Fragment>
    )
}
